config:
  swagger:
    title: API (ms-login-augt)
    description: This contract have the specifications of the dojo aug
    terms: https://google.com
    licence: apache 2.0
    licenceUrl: https://google.com
    version: 1.0
    contact:
      name: Globant
      url: https://google.com
      email: email@gmail.com


spring:
  application:
    name: ms-login-augt
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  output:
    ansi.enabled: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=augmented"
    username: "postgres"
    password: "padi"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        ddl-auto: update
        generate-ddl: true
api:
  login:
    url: api/v1/login

management:
  security:
    enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

logging:
  level:
    org:
      springframework:
        web: DEBUG